services:
  fastapi:
    build: .
    container_name: mcp-fastapi
    command: uv run uvicorn src.fastapi_app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped